<?php



/**
 * Skeleton subclass for performing query and update operations on the 'auditoria' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Tue Sep 23 16:17:59 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.Communikame
 */
class AuditoriaPeer extends BaseAuditoriaPeer {

} // AuditoriaPeer
