<?php



/**
 * Skeleton subclass for performing query and update operations on the 'permissao' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Tue Sep  9 19:09:55 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.Communikame
 */
class PermissaoQuery extends BasePermissaoQuery {
	/**
	 * Retorna uma query para selecionar as permissões disponíveis para o
	 * usuário logado. Se não houver usuário logado, nenhum filtro será aplicado
	 * e a consulta corresponderá a todas as permissões cadastradas.
	 * @param string $modelAlias (opcional) Alias usado na consulta. O padrão é
	 * <code>p</code>.
	 * @return PermissaoQuery
	 * @static
	 */
	public static function getDisponiveis($modelAlias = 'p')
	{
		return self::create($modelAlias)
			->filterByNivel(Usuario::atual()->getNivel(), Criteria::LESS_EQUAL);
	}
} // PermissaoQuery
