<?php



/**
 * Skeleton subclass for performing query and update operations on the 'usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Sat Sep  6 02:37:20 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.Communikame
 */
class UsuarioPeer extends BaseUsuarioPeer {

} // UsuarioPeer
